version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
    networks:
      - shared-inventory-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - shared-inventory-network

networks:
  shared-inventory-network:
    driver: bridge
